compilers:
- compiler:
    spec: gcc@=8.1.0
    paths:
      cc: /project/ukmo/rhel7/fortran/opt/gfortran/packages/gcc/8.1.0/bin/gcc
      cxx: /project/ukmo/rhel7/fortran/opt/gfortran/packages/gcc/8.1.0/bin/g++
      f77: /project/ukmo/rhel7/fortran/opt/gfortran/packages/gcc/8.1.0/bin/gfortran
      fc: /project/ukmo/rhel7/fortran/opt/gfortran/packages/gcc/8.1.0/bin/gfortran
    flags: {}
    operating_system: rhel7
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
