packages:
  flex:
    externals:
    - spec: flex@2.5.37+lex
      prefix: /usr
    buildable: false
  diffutils:
    externals:
    - spec: diffutils@3.3
      prefix: /usr
    buildable: false
  tar:
    externals:
    - spec: tar@1.26
      prefix: /usr
    buildable: false
  pkg-config:
    externals:
    - spec: pkg-config@0.27.1
      prefix: /usr
    buildable: false
  openssl:
    externals:
    - spec: openssl@1.0.2k-fips
      prefix: /usr
    buildable: false
  findutils:
    externals:
    - spec: findutils@4.5.11
      prefix: /usr
    buildable: false
  gmake:
    externals:
    - spec: gmake@3.82
      prefix: /usr
    buildable: false
  curl:
    externals:
    - spec: curl@7.29.0+ldap
      prefix: /usr
    buildable: false
  libtool:
    externals:
    - spec: libtool@2.4.2
      prefix: /usr
    buildable: false
  doxygen:
    externals:
    - spec: doxygen@1.8.5+graphviz~mscgen
      prefix: /usr
    buildable: false
  automake:
    externals:
    - spec: automake@1.13.4
      prefix: /usr
    buildable: false
  groff:
    externals:
    - spec: groff@1.22.2
      prefix: /usr
    buildable: false
  texinfo:
    externals:
    - spec: texinfo@5.1
      prefix: /usr
    buildable: false
  autoconf:
    externals:
    - spec: autoconf@2.69
      prefix: /usr
    buildable: false
  openssh:
    externals:
    - spec: openssh@7.4p1
      prefix: /usr
    buildable: false
  binutils:
    externals:
    - spec: binutils@2.27.44
      prefix: /usr
    buildable: false
  m4:
    externals:
    - spec: m4@1.4.16
      prefix: /usr
    buildable: false
  gawk:
    externals:
    - spec: gawk@4.0.2
      prefix: /usr
    buildable: false
  ninja:
    externals:
    - spec: ninja@1.10.2
      prefix: /usr
    buildable: false
  bison:
    externals:
    - spec: bison@3.0.4
      prefix: /usr
    buildable: false
  git:
    externals:
    - spec: git@2.24.4+tcltk
      prefix: /usr
    buildable: false
  git-lfs:
    externals:
    - spec: git-lfs@2.10.0
      prefix: /usr
    buildable: false
  coreutils:
    externals:
    - spec: coreutils@8.22
      prefix: /usr
    buildable: false
  subversion:
    externals:
    - spec: subversion@1.9.12
      prefix: /usr
    buildable: false
  slurm:
    externals:
    - spec: slurm@17.02.10
      prefix: /usr
    buildable: false
  libfabric:
    externals:
    - spec: libfabric@1.7.2
      prefix: /usr
    buildable: false
