# 1. Build base image with Docker
# 2. Build spack packages and save to binary cache
# 3. Build CI packages with dependencies for that package only
# 4. Build full container with all of Jopa
# 5. Convert Jopa docker container to Apptainer

stages:
    - setup
    - base
    - generate
    - spack-build
    - docker
    - apptainer
    - clean

variables:
    DOCKER_REGISTRY: '172.17.0.2:5000'
    DOCKER_PERSIST: '/scratch/gitlab-runner/'
    SPACK_CACHE: '${DOCKER_PERSIST}/${CI_PROJECT_PATH}/spack'

setup:
    stage: setup
    tags: [docker]
    script:
        - mkdir -p "${SPACK_CACHE}"
        - chmod a+rwX "$SPACK_CACHE"

base:
    stage: base
    tags: [docker]
    image: &kaniko_image
        name: gcr.io/kaniko-project/executor:debug
        entrypoint: [""]
    script: &kaniko_build
        - mkdir -p /kaniko/.docker
        - |
            cat > /kaniko/.docker/config.json <<EOF
            {"auths": {
                "$CI_DEPENDENCY_PROXY_SERVER": {
                    "auth": "$(printf "%s:%s" ${CI_DEPENDENCY_PROXY_USER} "${CI_DEPENDENCY_PROXY_PASSWORD}" | base64 | tr -d '\n')"
                }
            }}
            EOF
        - echo /kaniko/executor
            --context "${CI_PROJECT_DIR}"
            --dockerfile "${CI_PROJECT_DIR}/containers/${DOCKERFILE}"
            --destination "${DOCKER_REGISTRY}/${DEST}"
            --build-arg "DOCKER_REGISTRY=${DOCKER_REGISTRY}"
            --build-arg "SPACK_CACHE=${SPACK_CACHE}"
            --build-arg "CONTAINER_ENV=${CONTAINER_ENV}"
            --cache=true
        - /kaniko/executor
            --context "${CI_PROJECT_DIR}"
            --dockerfile "${CI_PROJECT_DIR}/containers/${DOCKERFILE}"
            --destination "${DOCKER_REGISTRY}/${DEST}"
            --build-arg "DOCKER_REGISTRY=${DOCKER_REGISTRY}"
            --build-arg "SPACK_CACHE=${SPACK_CACHE}"
            --build-arg "CONTAINER_ENV=${CONTAINER_ENV}"
            --cache=true
    variables:
        DOCKERFILE: base.docker
        DEST: spack-base:latest
        CONTAINER_ENV: base


generate:
    stage: generate
    tags: [docker]
    image: 
        name: localhost:5000/spack-base:latest
        entrypoint: [""]
        pull_policy: always
    script:
        - /bin/entrypoint.sh ./ci/generate.sh
    artifacts:
      paths:
        - "$CI_PROJECT_DIR/artifacts"
      expire_in: 1 day

spack build:
    stage: spack-build
    trigger:
      include:
        - artifact: artifacts/pipeline.yml
          job: generate
      strategy: depend

docker:
    stage: docker
    image: *kaniko_image
    script: *kaniko_build
    variables:
        DOCKERFILE: spack-env.docker
        CONTAINER_ENV: lfric-v0-gcc@8.5.0-openmpi@4.1.4
        DEST: lfric-v0-gcc-openmpi:latest
