#!/bin/bash

# Find the real rose, and run its command inside the container

function find_wrapped_cmd() {
    CMD="$1"

    hash "$CMD"
    ORIGINAL=$(hash -t "$CMD")

    PATH=$(echo ":$PATH:" | sed -e "s#:$(dirname "$ORIGINAL"):#:#g" -e "s#^:\(.*\):\$#\1#")

    hash "$CMD"
    WRAPPED=$(hash -t "$CMD")

    echo "$WRAPPED"
}

REAL=$(find_wrapped_cmd rose)

imagerun $REAL "$@"
