#!/bin/bash

# Find the real rose, and run its command inside the container

function find_wrapped_cmd() {
    CMD="$1"

    hash "$CMD"
    ORIGINAL=$(hash -t "$CMD")

    PATH=$(echo ":$PATH:" | sed -e "s#:$(dirname "$ORIGINAL"):#:#g" -e "s#^:\(.*\):\$#\1#")

    hash "$CMD"
    WRAPPED=$(hash -t "$CMD")

    echo "$WRAPPED"
}

REAL=$(find_wrapped_cmd rose)

# If this is a MPI command add imagerun so it works across multiple nodes
if [ "$2" = "mpi-launch" ]; then
    # Give the full path to the host mpirun
    if [ ( -n "$HOST_MPI" ) -a ( "${ROSE_LAUNCHER:-mpirun}" = "mpirun" ) ]; then
        ROSE_LAUNCHER=$HOST_MPI/bin/mpirun
    fi

    ROSE_LAUNCHER_PREOPTS=${ROSE_LAUNCHER_PREOPTS:-$($REAL config -E \
        --default= $ROSE_NS launcher-preopts.$ROSE_LAUNCHER_BASE)}
    ROSE_LAUNCHER_PREOPTS="${ROSE_LAUNCHER_PREOPTS} imagerun"
fi

imagerun $REAL "$@"
