compilers:
- compiler:
    spec: intel@2021.8.0
    paths:
      cc: /apps/intel-oneapi/compiler/2023.0.0/linux/bin/intel64/icc
      cxx: /apps/intel-oneapi/compiler/2023.0.0/linux/bin/intel64/icpc
      f77: /apps/intel-oneapi/compiler/2023.0.0/linux/bin/intel64/ifort
      fc: /apps/intel-oneapi/compiler/2023.0.0/linux/bin/intel64/ifort
    flags:
      ldlibs: -limf
    operating_system: rocky8
    target: x86_64
    modules: []
    extra_rpaths:
        - /apps/intel-oneapi/compiler/2023.0.0/linux/compiler/lib/intel64_lin
    environment:
        prepend_path:
            LD_LIBRARY_PATH: /apps/intel-oneapi/compiler/2023.0.0/linux/compiler/lib/intel64_lin
