compilers:
- compiler:
    spec: intel@2021.8.0
    paths:
      cc:  /apps/intel-ct/wrapper/icc
      cxx: /apps/intel-ct/wrapper/icpc
      f77: /apps/intel-ct/wrapper/ifort
      fc:  /apps/intel-ct/wrapper/ifort
    operating_system: rocky8
    target: x86_64
    extra_rpaths:
        - /apps/intel-ct/2021.8.0/compiler/linux/compiler/lib/intel64_lin
        - /apps/openmpi/4.1.4/lib/Intel
    modules:
        - intel-compiler/2021.8.0
    environment:
      append_path:
        LD_LIBRARY_PATH:: "/apps/intel-ct/2021.8.0/compiler/linux/compiler/lib/intel64_lin:/apps/openmpi/4.1.4/lib/Intel"
