compilers:
- compiler:
    spec: intel@2021.8.0
    paths:
      cc:  /apps/intel-ct/wrapper/icc
      cxx: /apps/intel-ct/wrapper/icpc
      f77: /apps/intel-ct/wrapper/ifort
      fc:  /apps/intel-ct/wrapper/ifort
    operating_system: rocky8
    target: x86_64
    modules:
        - intel-compiler/2021.8.0
