compilers:
- compiler:
    spec: intel@2021.8.0
    paths:
      #cc: /apps/intel-oneapi/compiler/2023.0.0/linux/bin/intel64/icc
      #cxx: /apps/intel-oneapi/compiler/2023.0.0/linux/bin/intel64/icpc
      #f77: /apps/intel-oneapi/compiler/2023.0.0/linux/bin/intel64/ifort
      #fc: /apps/intel-oneapi/compiler/2023.0.0/linux/bin/intel64/ifort
      cc:  /apps/intel-ct/wrapper/icc
      cxx: /apps/intel-ct/wrapper/icpc
      f77: /apps/intel-ct/wrapper/ifort
      fc:  /apps/intel-ct/wrapper/ifort
    operating_system: rocky8
    target: x86_64
    modules:
        - intel-compiler/2021.8.0
    #flags:
    #  ldlibs: -limf
    #extra_rpaths:
    #    - /apps/intel-oneapi/compiler/2023.0.0/linux/compiler/lib/intel64_lin
    #environment:
    #    prepend_path:
    #        LD_LIBRARY_PATH: /apps/intel-oneapi/compiler/2023.0.0/linux/compiler/lib/intel64_lin
