compilers:
- compiler:
    spec: intel@2021.8.0
    paths:
      cc:  /apps/intel-ct/wrapper/icc
      cxx: /apps/intel-ct/wrapper/icpc
      f77: /apps/intel-ct/wrapper/ifort
      fc:  /apps/intel-ct/wrapper/ifort
    operating_system: rocky8
    target: x86_64
    extra_rpaths:
        - /apps/intel-ct/2021.8.0/compiler/linux/compiler/lib/intel64_lin
    modules:
        - intel-compiler/2021.8.0
- compiler:
    spec: gcc@12.2.0
    paths:
      cc:  /apps/gcc/12.2.0/wrappers/gcc
      cxx: /apps/gcc/12.2.0/wrappers/g++
      f77: /apps/gcc/12.2.0/wrappers/gfortran
      fc:  /apps/gcc/12.2.0/wrappers/gfortran
    operating_system: rocky8
    target: x86_64
    modules:
        - gcc/12.2.0
