modules:
    prefix_inspections:
        ./include:
            - CPATH
        ./lib:
            - LIBRARY_PATH
            - LD_LIBRARY_PATH
    default:
        roots:
            tcl: /scratch/$PROJECT/$USER/spack/modules
        enable:
            - tcl

        tcl:
            all:
                autoload: direct
            python:
                filter:
                    # Keep the rest of the mamba environment out
                    exclude_env_vars: ['CPATH','LIBRARY_PATH','LD_LIBRARY_PATH','PKG_CONFIG_PATH','CMAKE_PREFIX_PATH','MANPATH']
            openmpi%intel:
                environment:
                    prepend_path:
                        CPATH: '{prefix}/include/Intel'


