modules:
    prefix_inspections:
        ./include:
            - CPATH
        ./lib:
            - LIBRARY_PATH
            - LD_LIBRARY_PATH
    default:
        roots:
            tcl: /scratch/$PROJECT/$USER/spack/modules
        enable:
            - tcl

        tcl:
            all:
                autoload: direct
