packages:
  texinfo:
    externals:
    - spec: texinfo@6.5
      prefix: /usr
    buildable: false
  gmake:
    externals:
    - spec: gmake@4.2.1
      prefix: /usr
    buildable: false
  tar:
    externals:
    - spec: tar@1.30
      prefix: /usr
    buildable: false
  autoconf:
    externals:
    - spec: autoconf@2.69
      prefix: /usr
    buildable: false
  pkgconf:
    externals:
    - spec: pkgconf@1.4.2
      prefix: /usr
    buildable: false
  subversion:
    externals:
    - spec: subversion@1.10.2
      prefix: /usr
    buildable: false
  curl:
    externals:
    - spec: curl@7.61.1+gssapi+ldap+nghttp2
      prefix: /usr
    buildable: false
  libtool:
    externals:
    - spec: libtool@2.4.6
      prefix: /usr
    buildable: false
  coreutils:
    externals:
    - spec: coreutils@8.30
      prefix: /usr
    buildable: false
  automake:
    externals:
    - spec: automake@1.16.1
      prefix: /usr
    buildable: false
  findutils:
    externals:
    - spec: findutils@4.6.0
      prefix: /usr
    buildable: false
  diffutils:
    externals:
    - spec: diffutils@3.6
      prefix: /usr
    buildable: false
  cvs:
    externals:
    - spec: cvs@1.11.23
      prefix: /usr
    buildable: false
  m4:
    externals:
    - spec: m4@1.4.18
      prefix: /usr
    buildable: false
  swig:
    externals:
    - spec: swig@3.0.12
      prefix: /usr
    buildable: false
  groff:
    externals:
    - spec: groff@1.22.3
      prefix: /usr
    buildable: false
  gawk:
    externals:
    - spec: gawk@4.2.1
      prefix: /usr
    buildable: false
  git:
    externals:
    - spec: git@2.31.1~tcltk
      prefix: /usr
    buildable: false
  openssl:
    externals:
    - spec: openssl@1.1.1k
      prefix: /usr
    buildable: false
  cmake:
    externals:
    - spec: cmake@3.20.2
      prefix: /usr
    - spec: cmake@3.24.2
      modules:
      - cmake/3.24.2
    buildable: false
  flex:
    externals:
    - spec: flex@2.6.1+lex
      prefix: /usr
    buildable: false
  openssh:
    externals:
    - spec: openssh@8.0p1
      prefix: /usr
    buildable: false
  bison:
    externals:
    - spec: bison@3.0.4
      prefix: /usr
    buildable: false
  binutils:
    externals:
    - spec: binutils@2.30.117
      prefix: /usr
    buildable: false
  ninja:
    externals:
    - spec: ninja@1.8.2
      prefix: /usr
    buildable: false
  zlib:
    externals:
    - spec: zlib@1.2.11
      prefix: /usr
    buildable: false
  zstd:
    externals:
    - spec: zstd@1.4.4
      prefix: /usr
    buildable: false
  ncurses:
    externals:
        - spec: ncurses@6.1
          prefix: /usr
    buildable: false
    #openmpi:
    #  externals:
    #  - spec: openmpi@4.1.4
    #    modules:
    #    - openmpi/4.1.4
    #  buildable: false
    #netcdf-c:
    #  externals:
    #  - spec: netcdf-c@4.9.0+mpi ^hdf5@1.10.7+mpi
    #    modules:
    #    - netcdf/4.9.0p
    #  buildable: false
    #hdf5:
    #  externals:
    #  - spec: hdf5@1.10.7+mpi
    #    modules:
    #    - hdf5/1.10.7p
    #  buildable: false
  python:
    externals:
    - spec: python@3.11.0
      modules:
      - python3/3.11.0
      - python3-as-python
    buildable: false
  perl:
      externals:
          - spec: perl@5.26.3
            prefix: /usr
  boost:
      externals:
          - spec: boost@1.80.0
            modules:
                - boost/1.80.0
